version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    steps:
      - run:
          name: Test app
          command: go test -v -short --count=1 $(go list ./...)
      - run:
          name: Build and push image
          command: sh build_push_image_karsajobs.sh
  lint:
    docker:
      - image: docker/hadolint
    steps: 
      - checkout
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

workflows:
  build-and-push:
    jobs:
      - lint
      - build