orbs:
  docker: circleci/docker@2.2.0

version: 2.1

jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
        - checkout
        - run:
            name: list directory
            command: ls -la
        - run:
            name: The First Step
            command: |
                echo 'Hello World!'
                echo 'This is the delivery pipeline'
        - run:
            name: Hadolint
            command: |
                docker run --rm -i hadolint/hadolint < Dockerfile

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build