version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: |
            apt-get update && apt-get install -y hadolint
            hadolint Dockerfile
      - run:
          name: Test app
          command: go test -v -short --count=1 $(go list ./...)
      - run:
          name: Build and push image
          command: sh build_push_image_karsajobs.sh

workflows:
  version: 2.1
  build-and-push:
    jobs:
      - build