version: 2.1
jobs:
  build:
    docker:
      - image: hadolint/hadolint
    steps:
        - run:
            name: The First Step
            command: |
                echo 'Hello World!'
                echo 'This is the delivery pipeline'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build