version: 2.1

jobs:
  lint-dockerfile:
    docker:
        # hadolint
      - image: hadolint/hadolint
    steps:
        - checkout
        - run:
            name: Lint Dockerfile
            command: hadolint karsajobs/Dockerfile
  test-app:
    docker:
        - image: circleci/golang:1.16
    steps:
        - checkout
        - run:
            name: Test App
            command: cd karsajobs && go test -v -short --count=1 $(go list ./... )
  build-app-karsajobs:
    docker:
        - image: circleci/golang:1.16
    steps:
        - checkout
        - run:
            name: Build App Karsajobs
            command: sh build_push_image_karsajobs.sh

workflows:
    build-test-deploy:
        jobs:
        - lint-dockerfile
        - test-app
            requires:
                - lint-dockerfile
        - build-app-karsajobs:
            requires:
                - test-app