# membuat image docker dengan tag github package registry
docker build -t ghcr.io/azizrosyid/karsajobs:latest .

# login ke github package registry
echo $PASSWORD_GITHUB_PKG | docker login ghcr.io -u azizrosyid --password-stdin

# push image ke github package registry
docker push ghcr.io/azizrosyid/karsajobs:latest

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    steps:
      - run:
          name: Test app
          command: go test -v -short --count=1 $(go list ./...)
      - run:
          name: Build and push image
          command: sh build_push_image_karsajobs.sh
  lint:
    docker:
      - image: docker/hadolint
    steps: 
      - checkout
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

workflows:
  lint:
    jobs:
      - checkout
      - docker/hadolint:
          dockerfile: Dockerfile
          ignore: DL3008

  build-and-push:
    jobs:
      - build