name: build-and-push
on:
  push:
    branches:
      - karsajobs

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint-dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "Dockerfile"
      - name: install-go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: test-app
        run: go test -v -short --count=1 $(go list ./...)
      - name: login-to-ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build-app-karsajobs
        run: sh build_push_image_karsajobs.sh